name: pertinet
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.2
  - pytorch-cuda=11.8
  - pyg=2.5
  - numpy=1.26
  - pandas=2.2
  - scikit-learn=1.4
  - scipy=1.12
  - matplotlib=3.8
  - seaborn=0.13
  - biopython=1.83
  - pip
  - pip:
      - gvp-pytorch==0.4.1
      - fair-esm==2.0.0
